// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ CORRECT Configuration matching google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrUry4OMHdoX1FWduxqlW4saArn833mIU',
    appId: '1:756502130603:android:c06c99cdd26cd68609acee',
    messagingSenderId: '756502130603',
    projectId: 'zonedatabase-d0432-48b05',
    storageBucket: 'zonedatabase-d0432-48b05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrUry4OMHdoX1FWduxqlW4saArn833mIU', // Use same API key or generate iOS-specific one
    appId: '1:756502130603:ios:GENERATE_THIS_IN_FIREBASE', // You need to add iOS app in Firebase Console
    messagingSenderId: '756502130603',
    projectId: 'zonedatabase-d0432-48b05',
    storageBucket: 'zonedatabase-d0432-48b05.firebasestorage.app',
    iosBundleId: 'com.example1.roadeyeai',
  );
}